package colors

import "github.com/charmbracelet/lipgloss"

var Rosewater = lipgloss.Color("#f5e0dc")
var Flamingo = lipgloss.Color("#f2cdcd")
var Pink = lipgloss.Color("##f5c2e7")
var Red = lipgloss.Color("#f38ba8")
var Maroon = lipgloss.Color("#eba0ac")
var Peach = lipgloss.Color("#fab387")
var Yellow = lipgloss.Color("#f9e2af")
var Green = lipgloss.Color("#a6e3a1")
var Teal = lipgloss.Color("#94e2d5")
var Sky = lipgloss.Color("#89dceb")
var Sapphire = lipgloss.Color("#74c7ec")
var Blue = lipgloss.Color("#89b4fa")
var Lavender = lipgloss.Color("#b4befe")
var Text = lipgloss.Color("#cdd6f4")
var Subtext1 = lipgloss.Color("#bac2de")
var Subtext0 = lipgloss.Color("#a6adc8")
var Overlay2 = lipgloss.Color("#9399b2")
var Overlay1 = lipgloss.Color("#7f849c")
var Overlay0 = lipgloss.Color("#6c7086")
var Surface2 = lipgloss.Color("#585b70")
var Surface1 = lipgloss.Color("#45475a")
var Surface0 = lipgloss.Color("#313244")
var Base = lipgloss.Color("#1e1e2e")
var Mantle = lipgloss.Color("#181825")
var Crust = lipgloss.Color("#11111b")
